/**
 * S6 — Production: validate or bootstrap generated code from specs + SDDs.
 * PRD §7.1 S6, gates G3 (impact resolved) + G4 (codegen complete).
 *
 * Phase 1 dual-mode:
 *   - **Validate mode** (default): Check if code files exist in src/generated/
 *     with valid provenance headers. If missing → return `blocked` so Claude
 *     can launch implementer + test-author subagents, then resume.
 *   - **Bootstrap mode** (KEYSTONE_BOOTSTRAP=1 or tests): Template-generate
 *     code like Phase 0 M4 for deterministic testing.
 */
import { resolve, dirname } from "node:path";
import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import type { StationContext, StationOutcomeDraft } from "../orchestrator/stations.js";
import type {
  ImpactReport,
  ProductionReport,
  GeneratedFile,
  TraceIndex,
} from "./types.js";
import type { SpecFile } from "../types.js";
import { loadAllSpecs } from "../spec/loader.js";

const isBootstrap = () =>
  process.env.KEYSTONE_BOOTSTRAP === "1" || process.env.VITEST === "true";

// ── Provenance header ──────────────────────────────────────────────

function provenanceHeader(specId: string, specVersion: string, sddId: string, runId: string): string {
  return [
    `// @keystone-owner    ${specId}`,
    `// @spec-version      ${specVersion}`,
    `// @sdd-source        ${sddId}`,
    `// @generated-by      keystone@0.0.1`,
    `// @generated-at      ${new Date().toISOString()}`,
    `// @run-id            ${runId}`,
    "",
  ].join("\n");
}

// ── Validation (scan src/generated/ for files with provenance) ────

function findGeneratedFiles(dir: string, base: string): string[] {
  if (!existsSync(dir)) return [];
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = resolve(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...findGeneratedFiles(full, base));
    } else if (entry.endsWith(".ts") || entry.endsWith(".py") || entry.endsWith(".go")) {
      results.push(full);
    }
  }
  return results;
}

function validateGeneratedCode(
  repoRoot: string,
  affectedIds: string[],
): { files: GeneratedFile[]; issues: string[] } {
  const srcDir = resolve(repoRoot, "src", "generated");
  const testDir = resolve(repoRoot, "tests", "generated");
  const files: GeneratedFile[] = [];
  const issues: string[] = [];

  const srcFiles = findGeneratedFiles(srcDir, repoRoot);
  const testFiles = findGeneratedFiles(testDir, repoRoot);

  if (srcFiles.length === 0) {
    issues.push("No implementation files in src/generated/");
    return { files, issues };
  }

  // Check provenance headers in implementation files
  for (const absPath of srcFiles) {
    const content = readFileSync(absPath, "utf8");
    // Provenance header: // @keystone-owner (TS) or # @keystone-owner (Python)
    const ownerMatch = content.match(/@keystone-owner\s+(\S+)/);
    if (!ownerMatch) {
      issues.push(`${absPath}: missing @keystone-owner provenance header`);
      continue;
    }
    const relPath = absPath.replace(repoRoot + "\\", "").replace(repoRoot + "/", "").replace(/\\/g, "/");
    files.push({ path: relPath, owner_spec_id: ownerMatch[1], type: "implementation" });
  }

  // Check test files
  for (const absPath of testFiles) {
    const content = readFileSync(absPath, "utf8");
    const ownerMatch = content.match(/@keystone-owner\s+(\S+)/);
    const relPath = absPath.replace(repoRoot + "\\", "").replace(repoRoot + "/", "").replace(/\\/g, "/");
    files.push({
      path: relPath,
      owner_spec_id: ownerMatch?.[1] ?? "unknown",
      type: "test",
    });
  }

  // Check that affected spec IDs have at least one implementation file
  const ownedIds = new Set(files.filter((f) => f.type === "implementation").map((f) => f.owner_spec_id));
  for (const id of affectedIds) {
    if (id.startsWith("PROJECT") || id.startsWith("FEAT")) continue; // FEAT/PROJECT don't need code directly
    if (!ownedIds.has(id)) {
      issues.push(`No implementation file owned by ${id}`);
    }
  }

  return { files, issues };
}

// ── Ownership + trace update ──────────────────────────────────────

function updateOwnership(repoRoot: string, files: GeneratedFile[]): void {
  const ownershipPath = resolve(repoRoot, ".trace", "ownership.yaml");
  const ownership: Record<string, string> = {};
  for (const f of files) {
    if (f.type === "implementation") ownership[f.path] = f.owner_spec_id;
  }
  const content = [
    "# File-ownership manifest — PRD §9.5.1, §10.2",
    "# Auto-generated by S6 production station.",
    "version: 1",
    `ownership:`,
    ...Object.entries(ownership).map(([path, id]) => `  "${path}": "${id}"`),
    "",
  ].join("\n");
  writeFileSync(ownershipPath, content, "utf8");
}

function updateTraceIndex(repoRoot: string, files: GeneratedFile[]): void {
  const indexPath = resolve(repoRoot, ".trace", "index.json");
  if (!existsSync(indexPath)) return;
  const index: TraceIndex = JSON.parse(readFileSync(indexPath, "utf8"));
  for (const file of files) {
    const entry = index.entries.find((e) => e.spec_id === file.owner_spec_id);
    if (!entry) continue;
    if (file.type === "implementation" && !entry.implementations.includes(file.path)) {
      entry.implementations.push(file.path);
    } else if (file.type === "test" && !entry.tests.includes(file.path)) {
      entry.tests.push(file.path);
    }
  }
  writeFileSync(indexPath, JSON.stringify(index, null, 2) + "\n", "utf8");
}

// ── Bootstrap (template generation) ───────────────────────────────

function generateEntitySchema(ent: SpecFile, runId: string): { path: string; content: string } {
  const fields = (ent.data.fields ?? []) as Array<Record<string, unknown>>;
  const header = provenanceHeader(ent.data.id, ent.data.version, `SDD-DATA-${ent.data.id}`, runId);
  const columnLines = fields.map((f) => {
    const name = String(f.name);
    const type = String(f.type);
    let col = type === "integer" ? `integer("${name}")` : `text("${name}")`;
    if (f.pk) col += `.primaryKey()`;
    return `  ${name}: ${col},`;
  });
  const tableName = ent.data.title.toLowerCase().replace(/\s+/g, "_") + "s";
  return {
    path: `src/generated/auth/entities/${ent.data.id.toLowerCase().replace(/-/g, "_")}.schema.ts`,
    content: `${header}import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";\n\nexport const ${tableName} = sqliteTable("${tableName}", {\n${columnLines.join("\n")}\n});\n`,
  };
}

function generateEntityValidator(ent: SpecFile, runId: string): { path: string; content: string } {
  const fields = (ent.data.fields ?? []) as Array<Record<string, unknown>>;
  const header = provenanceHeader(ent.data.id, ent.data.version, `SDD-DATA-${ent.data.id}`, runId);
  const zodFields = fields.map((f) => {
    const name = String(f.name);
    const type = String(f.type);
    let z: string;
    switch (type) {
      case "uuid": z = "z.string().uuid()"; break;
      case "integer": z = "z.number().int()"; break;
      case "timestamp": z = "z.string().datetime().nullable()"; break;
      case "enum": {
        const values = (f.values as string[]) ?? [];
        z = values.length > 0 ? `z.enum([${values.map((v) => `"${v}"`).join(", ")}])` : "z.string()";
        break;
      }
      default: z = "z.string()";
    }
    if (f.required === false) z += ".optional()";
    return `  ${name}: ${z},`;
  });
  const schemaName = ent.data.title.replace(/\s+/g, "") + "Schema";
  return {
    path: `src/generated/auth/entities/${ent.data.id.toLowerCase().replace(/-/g, "_")}.validator.ts`,
    content: `${header}import { z } from "zod";\n\nexport const ${schemaName} = z.object({\n${zodFields.join("\n")}\n});\n\nexport type ${ent.data.title.replace(/\s+/g, "")} = z.infer<typeof ${schemaName}>;\n`,
  };
}

function generateService(req: SpecFile, runId: string): { path: string; content: string } {
  const header = provenanceHeader(req.data.id, req.data.version, `SDD-COMP-FEAT-AUTH`, runId);
  const acs = req.data.acceptance_criteria ?? [];
  const content = `${header}/**
 * Auth service — generated from ${req.data.id} v${req.data.version}.
 * Pure functions, no I/O. Phase 0 template.
 */

export interface User {
  id: string;
  email: string;
  password_hash: string;
  status: "active" | "suspended";
  failed_login_count: number;
  locked_until: string | null;
}

export interface LoginResult {
  success: boolean;
  token?: string;
  error?: string;
  status_code: number;
}

const MAX_FAILED_ATTEMPTS = 5;

/**
 * Verify login credentials.
 * ${acs.map((ac) => `${ac.id}: given ${ac.given}, when ${ac.when}, then ${ac.then}`).join("\n * ")}
 */
export function verifyLogin(
  email: string,
  password: string,
  user: User | null,
  verifyHash: (hash: string, password: string) => boolean = () => true,
): LoginResult {
  if (!user) return { success: false, error: "user_not_found", status_code: 401 };
  if (user.status === "suspended") return { success: false, error: "account_suspended", status_code: 403 };
  if (user.locked_until) {
    const lockExpiry = new Date(user.locked_until);
    if (lockExpiry > new Date()) return { success: false, error: "account_locked", status_code: 429 };
  }
  if (user.failed_login_count >= MAX_FAILED_ATTEMPTS) return { success: false, error: "account_locked", status_code: 429 };
  if (!verifyHash(user.password_hash, password)) return { success: false, error: "invalid_credentials", status_code: 401 };
  const token = \`token_\${user.id}_\${Date.now()}\`;
  return { success: true, token, status_code: 200 };
}
`;
  return { path: `src/generated/auth/services/auth.service.ts`, content };
}

function generateTests(req: SpecFile, runId: string): { path: string; content: string } {
  const header = provenanceHeader(req.data.id, req.data.version, `SDD-COMP-FEAT-AUTH`, runId);
  const content = `${header}import { describe, it, expect } from "vitest";
import { verifyLogin } from "../../../src/generated/auth/services/auth.service.js";
import type { User } from "../../../src/generated/auth/services/auth.service.js";

const validUser: User = {
  id: "u1", email: "test@example.com", password_hash: "hashed_password",
  status: "active", failed_login_count: 0, locked_until: null,
};

describe("Auth Service — generated from ${req.data.id}", () => {
  it("returns token on valid credentials (AC-AUTH-001-01)", () => {
    const result = verifyLogin("test@example.com", "correct", validUser, () => true);
    expect(result.success).toBe(true);
    expect(result.token).toBeDefined();
    expect(result.status_code).toBe(200);
  });
  it("returns 401 on invalid credentials", () => {
    const result = verifyLogin("test@example.com", "wrong", validUser, () => false);
    expect(result.success).toBe(false);
    expect(result.status_code).toBe(401);
  });
  it("returns 401 when user not found", () => {
    const result = verifyLogin("nobody@example.com", "pwd", null);
    expect(result.success).toBe(false);
    expect(result.status_code).toBe(401);
  });
  it("returns 429 when failed_login_count >= 5 (AC-AUTH-001-02)", () => {
    const lockedUser: User = { ...validUser, failed_login_count: 5 };
    const result = verifyLogin("test@example.com", "any", lockedUser);
    expect(result.success).toBe(false);
    expect(result.status_code).toBe(429);
  });
  it("returns 403 when account suspended", () => {
    const suspendedUser: User = { ...validUser, status: "suspended" };
    const result = verifyLogin("test@example.com", "any", suspendedUser);
    expect(result.success).toBe(false);
    expect(result.status_code).toBe(403);
  });
});
`;
  return { path: `tests/generated/auth/auth.spec.ts`, content };
}

// ── Python templates ──────────────────────────────────────────────

function pyProvenanceHeader(specId: string, specVersion: string, sddId: string, runId: string): string {
  return [
    `# @keystone-owner    ${specId}`,
    `# @spec-version      ${specVersion}`,
    `# @sdd-source        ${sddId}`,
    `# @generated-by      keystone@0.0.1`,
    `# @generated-at      ${new Date().toISOString()}`,
    `# @run-id            ${runId}`,
    "",
  ].join("\n");
}

function generatePythonModel(ent: SpecFile, runId: string): { path: string; content: string } {
  const fields = (ent.data.fields ?? []) as Array<Record<string, unknown>>;
  const header = pyProvenanceHeader(ent.data.id, ent.data.version, `SDD-DATA-${ent.data.id}`, runId);
  const fieldLines = fields.map((f) => {
    const name = String(f.name);
    const type = String(f.type);
    let pyType: string;
    switch (type) {
      case "uuid": pyType = "str"; break;
      case "string": pyType = "str"; break;
      case "integer": pyType = "int"; break;
      case "timestamp": pyType = "str | None"; break;
      case "enum": pyType = "str"; break;
      case "boolean": pyType = "bool"; break;
      default: pyType = "str";
    }
    const default_ = f.required === false ? " = None" : f.default !== undefined ? ` = ${JSON.stringify(f.default)}` : "";
    return `    ${name}: ${pyType}${default_}`;
  });
  const className = ent.data.title.replace(/\s+/g, "");
  return {
    path: `src/generated/auth/models/${ent.data.id.toLowerCase().replace(/-/g, "_")}.py`,
    content: `${header}from pydantic import BaseModel, EmailStr\n\n\nclass ${className}(BaseModel):\n${fieldLines.join("\n")}\n`,
  };
}

function generatePythonService(req: SpecFile, runId: string): { path: string; content: string } {
  const header = pyProvenanceHeader(req.data.id, req.data.version, `SDD-COMP-FEAT-AUTH`, runId);
  const acs = req.data.acceptance_criteria ?? [];
  return {
    path: `src/generated/auth/services/auth_service.py`,
    content: `${header}\"\"\"Auth service — generated from ${req.data.id} v${req.data.version}.\"\"\"
from dataclasses import dataclass


@dataclass
class LoginResult:
    success: bool
    token: str | None = None
    error: str | None = None
    status_code: int = 200


MAX_FAILED_ATTEMPTS = 5


def verify_login(
    email: str,
    password: str,
    user: dict | None,
    verify_hash=lambda h, p: True,
) -> LoginResult:
    \"\"\"
    Verify login credentials.
    ${acs.map((ac) => `${ac.id}: given ${ac.given}, when ${ac.when}, then ${ac.then}`).join("\n    ")}
    \"\"\"
    if user is None:
        return LoginResult(success=False, error="user_not_found", status_code=401)
    if user.get("status") == "suspended":
        return LoginResult(success=False, error="account_suspended", status_code=403)
    if user.get("failed_login_count", 0) >= MAX_FAILED_ATTEMPTS:
        return LoginResult(success=False, error="account_locked", status_code=429)
    if not verify_hash(user.get("password_hash", ""), password):
        return LoginResult(success=False, error="invalid_credentials", status_code=401)
    token = f"token_{user['id']}_{hash(email)}"
    return LoginResult(success=True, token=token, status_code=200)
`,
  };
}

function generatePythonTests(req: SpecFile, runId: string): { path: string; content: string } {
  const header = pyProvenanceHeader(req.data.id, req.data.version, `SDD-COMP-FEAT-AUTH`, runId);
  return {
    path: `tests/generated/auth/test_auth.py`,
    content: `${header}\"\"\"Tests for auth service — generated from ${req.data.id}.\"\"\"
import pytest
from src.generated.auth.services.auth_service import verify_login


VALID_USER = {
    "id": "u1", "email": "test@example.com", "password_hash": "hashed",
    "status": "active", "failed_login_count": 0, "locked_until": None,
}


def test_valid_login_returns_token():
    result = verify_login("test@example.com", "correct", VALID_USER, lambda h, p: True)
    assert result.success is True
    assert result.token is not None
    assert result.status_code == 200


def test_invalid_password_returns_401():
    result = verify_login("test@example.com", "wrong", VALID_USER, lambda h, p: False)
    assert result.success is False
    assert result.status_code == 401


def test_user_not_found_returns_401():
    result = verify_login("nobody@example.com", "pwd", None)
    assert result.success is False
    assert result.status_code == 401


def test_lockout_returns_429():
    locked = {**VALID_USER, "failed_login_count": 5}
    result = verify_login("test@example.com", "any", locked)
    assert result.success is False
    assert result.status_code == 429


def test_suspended_returns_403():
    suspended = {**VALID_USER, "status": "suspended"}
    result = verify_login("test@example.com", "any", suspended)
    assert result.success is False
    assert result.status_code == 403
`,
  };
}

// ── Stack detection + bootstrap dispatch ─────────────────────────

type StackLanguage = "typescript" | "python" | "go";

function detectStack(specs: SpecFile[]): StackLanguage {
  const project = specs.find((s) => s.data.type === "project");
  const stack = project?.data.stack as Record<string, unknown> | undefined;
  const lang = String(stack?.language ?? "typescript").toLowerCase();
  if (lang.includes("python")) return "python";
  if (lang.includes("go")) return "go";
  return "typescript";
}

function bootstrapCode(specs: SpecFile[], affectedIds: string[], runId: string, repoRoot: string): GeneratedFile[] {
  const affectedSet = new Set(affectedIds);
  const entSpecs = specs.filter((s) => s.data.type === "entity" && affectedSet.has(s.data.id));
  const reqSpecs = specs.filter((s) => s.data.type === "requirement" && affectedSet.has(s.data.id));
  const generatedFiles: GeneratedFile[] = [];
  const stack = detectStack(specs);

  for (const ent of entSpecs) {
    const generators = stack === "python"
      ? [generatePythonModel(ent, runId)]
      : [generateEntitySchema(ent, runId), generateEntityValidator(ent, runId)];
    for (const gen of generators) {
      const absPath = resolve(repoRoot, gen.path);
      mkdirSync(dirname(absPath), { recursive: true });
      writeFileSync(absPath, gen.content, "utf8");
      generatedFiles.push({ path: gen.path, owner_spec_id: ent.data.id, type: "implementation" });
    }
  }
  for (const req of reqSpecs) {
    const service = stack === "python" ? generatePythonService(req, runId) : generateService(req, runId);
    mkdirSync(dirname(resolve(repoRoot, service.path)), { recursive: true });
    writeFileSync(resolve(repoRoot, service.path), service.content, "utf8");
    generatedFiles.push({ path: service.path, owner_spec_id: req.data.id, type: "implementation" });

    const tests = stack === "python" ? generatePythonTests(req, runId) : generateTests(req, runId);
    mkdirSync(dirname(resolve(repoRoot, tests.path)), { recursive: true });
    writeFileSync(resolve(repoRoot, tests.path), tests.content, "utf8");
    generatedFiles.push({ path: tests.path, owner_spec_id: req.data.id, type: "test" });
  }
  return generatedFiles;
}

// ── Handler ───────────────────────────────────────────────────────

export function s6Handler(ctx: StationContext): StationOutcomeDraft {
  const impactPath = resolve(ctx.repoRoot, ".keystone", "impact-report.json");
  if (!existsSync(impactPath)) {
    return { verdict: "reject", message: "S6: impact-report.json missing" };
  }
  const impact: ImpactReport = JSON.parse(readFileSync(impactPath, "utf8"));

  if (impact.affected_ids.length === 0) {
    const report: ProductionReport = { run_id: ctx.runId, generated_files: [], verdict: "pass" };
    const outDir = resolve(ctx.repoRoot, ".keystone");
    mkdirSync(outDir, { recursive: true });
    writeFileSync(resolve(outDir, "production-report.json"), JSON.stringify(report, null, 2) + "\n", "utf8");
    return { verdict: "pass", message: "S6: No affected specs — skipping codegen.", report_path: ".keystone/production-report.json" };
  }

  let generatedFiles: GeneratedFile[];

  if (isBootstrap()) {
    // Bootstrap mode: template-generate code
    const specs = loadAllSpecs(resolve(ctx.repoRoot, "specs"), ctx.repoRoot);
    generatedFiles = bootstrapCode(specs, impact.affected_ids, ctx.runId, ctx.repoRoot);
  } else {
    // Validate mode: check if code exists with provenance
    const validation = validateGeneratedCode(ctx.repoRoot, impact.affected_ids);

    if (validation.files.length === 0) {
      return {
        verdict: "blocked",
        message: `S6: Awaiting code generation. Launch implementer + test-author subagents, then /keystone:resume. ${validation.issues.join("; ")}`,
      };
    }

    if (validation.issues.some((i) => i.includes("missing @keystone-owner"))) {
      return {
        verdict: "reject",
        message: `S6: Generated code has issues: ${validation.issues.join("; ")}`,
      };
    }

    generatedFiles = validation.files;
  }

  // Update ownership + trace index
  updateOwnership(ctx.repoRoot, generatedFiles);
  updateTraceIndex(ctx.repoRoot, generatedFiles);

  const report: ProductionReport = {
    run_id: ctx.runId,
    generated_files: generatedFiles,
    verdict: "pass",
  };
  const outDir = resolve(ctx.repoRoot, ".keystone");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, "production-report.json"), JSON.stringify(report, null, 2) + "\n", "utf8");

  const implCount = generatedFiles.filter((f) => f.type === "implementation").length;
  const testCount = generatedFiles.filter((f) => f.type === "test").length;
  return {
    verdict: "pass",
    message: `S6: ${generatedFiles.length} file(s) validated (${implCount} impl, ${testCount} test).`,
    report_path: ".keystone/production-report.json",
  };
}
